const chokidar = require('chokidar');
const http = require('http');
const fs = require('fs');
const path = require('path');

// Path to trigger file (will be created/modified to trigger Metro reload)
const triggerFile = path.join(__dirname, '..', '.reload-trigger.js');

// Watch files
const watcher = chokidar.watch([
  'public/**/*.{js,jsx,ts,tsx}',
  'package/**/*.{js,jsx,ts,tsx}',
  'App.js',
  'index.js'
], {
  ignored: /(^|[\/\\])\../, // ignore dotfiles
  persistent: true,
  ignoreInitial: true
});

// Function to trigger reload by modifying a file that Metro watches
function triggerReload() {
  try {
    // Create or modify trigger file to force Metro to detect change
    const timestamp = Date.now();
    const content = `// Auto-reload trigger file
// This file is auto-generated by auto-reload script
// Do not edit manually
export const reloadTrigger = ${timestamp};
`;
    
    fs.writeFileSync(triggerFile, content, 'utf8');
    console.log('✅ Reload triggered - Metro should auto-reload now');
    
    // Try multiple methods to ensure reload
    setTimeout(() => {
      // Method 1: Try HTTP request to Metro
      const req = http.request({
        hostname: 'localhost',
        port: 9002,
        path: '/reload',
        method: 'GET',
        timeout: 500
      }, () => {
        console.log('✅ HTTP reload signal sent');
      });
      
      req.on('error', () => {
        // Metro might not have this endpoint, that's okay
      });
      
      req.on('timeout', () => {
        req.destroy();
      });
      
      req.end();
    }, 100);
    
  } catch (error) {
    console.log('⚠️ Error triggering reload:', error.message);
    console.log('💡 Please press "r" in Metro terminal to reload manually');
  }
}

console.log('🔄 Auto-reload watcher started');
console.log('📝 Watching for file changes...');
console.log('💡 Make sure Metro bundler is running on port 9002');
console.log('');

watcher
  .on('change', (filePath) => {
    const relativePath = path.relative(process.cwd(), filePath);
    console.log(`📝 File changed: ${relativePath}`);
    console.log('🔄 Triggering auto-reload...');
    triggerReload();
    console.log('');
  })
  .on('error', (error) => {
    console.log('⚠️ Watcher error:', error);
  });

// Cleanup on exit
process.on('SIGINT', () => {
  watcher.close();
  if (fs.existsSync(triggerFile)) {
    fs.unlinkSync(triggerFile);
  }
  process.exit(0);
});

